name: testing

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      
      - name: Install Poetry
        run: pip install poetry
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      
      - name: Install dependencies 
        run: poetry install --no-root
      
      - name: Dependency Validation 
        run: poetry check

      - name: Cyclomatic Complexity
        run: poetry run radon cc src/ streamlit_app.py -a -s
      
      - name: Maintainability Index
        if: '!cancelled()'
        run: poetry run radon mi src/ streamlit_app.py -s
      
      - name: Style (PEP8)
        if: '!cancelled()'
        run: poetry run flake8 src/ tests/ streamlit_app.py
      
      - name: Unit Tests Pass Rate
        if: '!cancelled()'
        run: poetry run pytest --cov=src --cov-report=term-missing
      
      - name: Mutation tests for business_logic.py
        if: '!cancelled()'
        run: poetry run mutmut run --paths-to-mutate src/business_logic.py --runner "pytest tests/mutation/test_mutation_bl.py"
      
      - name: Line Coverage
        if: '!cancelled()'
        run: poetry run pytest --cov=src --cov-report=term-missing --cov-fail-under=70
      
      - name: Security Scan
        if: '!cancelled()'
        run: poetry run bandit -r src/ streamlit_app.py -ll
      
      - name: Performance Smoke Test
        if: '!cancelled()'
        run: poetry run locust -f tests/load/locustfile.py --headless -u 1 -r 1 -t 10s